dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

go:
  - 1.11.4

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  yarn: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - node_modules

before_install:
  - eval "$(GIMME_GO_VERSION=1.11.4 gimme)"
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar

install: true

script:
  # Unit-test and build server
  - cd server/
  - ./gradlew --console=plain build --info
  - cd ..

  # Unit-test and build integration server
  - cd github-integration/
  - ./gradlew --console=plain build --info
  - cd ..

  # Launch local zally server
  - cd server/
  - ./gradlew --console=plain bootRun > /dev/null &
  - echo $! > /tmp/zally_server.pid
  - cd ..

  # Wait until Spring Boot will start
  - while ! echo "GET / HTTP/1.0\n" | nc localhost 8000; do sleep 1; done

  # Test and build CLI
  - cd cli/zally
  - ./test.sh
  - ./test.sh integration
  - go build
  - cd $TRAVIS_BUILD_DIR

  # Kill Zally server instance
  - kill -9 `cat /tmp/zally_server.pid`

  # Unit-test web UI
  - cd web-ui
  - npm --version
  - nvm install 10
  - node --version
  - yarn --version
  - yarn install -q
  - yarn test
  - yarn build
  - cd $TRAVIS_BUILD_DIR

after_success:
  # Upload test code coverage report for Zally server to codacy
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r server/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally server to codecov
  - bash <(curl -s https://codecov.io/bash) -f server/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally integration server
  - bash <(curl -s https://codecov.io/bash) -f github-integration/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally CLI
  - bash <(curl -s https://codecov.io/bash) -f cli/zally/coverage.txt -f $TRAVIS_BUILD_DIR/web-ui/target/coverage/lcov.info
