# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  environment: 'd'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

step:
          #- script: gradlew build ; docker build -t $(dockerId)/$(imageName)
  displayName: Build docker images 
- script: cd server
  script: ./gradlew build
  script: docker build .

  #- task: AzureResourceGroupDeployment@2
  #displayName: 'Azure Create Docker Registry'
  #inputs:
  #  azureSubscription: 'vwt-dev Azure subscription'
  #  resourceGroupName: vwt-$(environment)-we-dat-crg-rg
  #  location: 'West Europe'
  #  csmFile: 'template/create_docker_registry_template.json'
  #  csmParametersFile: 'template/create_docker_registry_parameters.json'
