# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: zally-build

    #variables:
    #  environment: 'd'
    #  azureSubscriptionEndpoint: vwt-dev Azure subscription
    #  azureContainerRegistry: vwtdatdevcrg.azurecr.io

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    cd server
    ./gradlew build -x test
  displayName: Build zally server

- task: Docker@1
  displayName: Build $(Build.BuildIdServer) image
  inputs:
    command: build
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: server/Dockerfile
    #imageName: zally_server
    imageName: $(Build.BuildIdServer)

- task: Docker@1
  displayName: Build $(Build.BuildIdGui) image
  inputs:
    command: build
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: web-ui/Dockerfile
    #imageName: zally_webui
    imageName: $(Build.BuildIdGui)

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- task: Docker@1
  displayName: Push image ($(Build.Repository.Name))  ($(Build.BuildIdServer))
  inputs:
    command: push
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(Build.Repository.Name)/$(Build.BuildIdServer)

- task: Docker@1
  displayName: Push image ($(Build.BuildIdGui))
  inputs:
    command: push
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(Build.Repository.Name)/$(Build.BuildIdGui)
