# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  environment: 'd'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
          #- script: gradlew build ; docker build -t $(dockerId)/$(imageName)
- script: |
    cd server
    ./gradlew build
    docker build -t vwtdatdevcrg.azurecr.io/zally_server .
    docker login -u vwtdatdevcrg vwtdatdevcrg.azurecr.io
    docker push vwtdatdevcrg.azurecr.io/zally_server
  displayName: Build docker images 

  #- task: Docker@1
  #displayName: Container registry login
  #inputs:
  #  command: login
  #  containerregistrytype: Container Registry
  #  dockerRegistryEndpoint: Contoso
