builds:
  - binary: zally
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: main
    format: tar.gz
    replacements:
      amd64: 64bit
      darwin: macOS
